## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


а) Перемножить нельзя
б) AB 2X3
в) AB 8X8, BA 3X3
г) АВ BA 4X4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


$A+B$=$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 &  5
\end{pmatrix}$

$AB$=$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1*4 + -2*0 & 1*-1 -2*5 \\ 
3*4 + 0*0 & 3*-1 + 0*5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$BA$= $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ * $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$  = $\begin{pmatrix}
4*1 + -1*3 & 4*-2 + -1*0 \\ 
0*1 + 5*3 & 0*-2 + 5*0
\end{pmatrix}$ = $\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [8]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BА\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BА
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$+$-2B=\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}$+$4C\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=$ $\begin{pmatrix}
3+0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}=$ $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [14]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3*A - 2*B + 4*C}')

Матрица 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [12]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'Матрица 𝐴*𝐴𝑇\n{np.dot(A,A.T)}')
print(f'Матрица 𝐴𝑇*𝐴\n{np.dot(A.T,A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица 𝐴*𝐴𝑇
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица 𝐴𝑇*𝐴
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.